version: '3.7'
services:
  mysql:
    image: postgres:13.11-alpine3.17
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
